name: build
on:
  push:
    branches: [ main ]
    paths:
      - '!README.md'
  pull_request:
    branches: [ main ]
    paths:
      - '!README.md'
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

name: release
on:
  release:
    types:
      - created
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish
      env:
        crates_token: ${{ secrets.crates_token }}
      run: cargo publish --locked --token ${crates_token}  --verbose